### PR TITLE
Add CT8 hosting support

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Codanovia** [comment]
I can't do it right now because of this:
d2565d587f22726064d624ff3ed2ef02\
If the number will decrease, I'm going to merge this pull request

**Comment by ghost** [comment]
I can give my account. @Codanovia

**Comment by Codanovia** [comment]
You don't need to do this. Number has been already decreased to 1461/1500

**Comment by ghost** [comment]
Ok.

**Comment by Codanovia** [comment]
Nevermind, give me your account (it takes infinity to create an account) @ItzLennyFace

**Comment by ghost** [comment]
So PM to me @Codanovia

**Pull request merged**
